version: "3"

services:
  nginx:
    image: appliedblockchain/strading-nginx-build
    build:
      args:
        VERSION: 1.19.7-alpine
      context: .
    ports:
      - 80:80
    volumes:
      - ./docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf